### ISSUE TITLE
PM Archival errors to Admins for their manual revision

### ISSUE THREAD

**Issue by Dthen** [Dthen/CubeBox#28]

**Comment by davidwarrington** [comment]
@Dthen Not sure what your thoughts on this are, but I think in the long term we ought to have a separate error handler. So rather than simply throwing an error or using `console.error()`, we'd push errors to the handler, which would in turn decide if it needs logging to the console, if it needs printing to an actual log file, and who it needs to PM.

Also as either an alternative to PMing people, or an addition, we could have a generic staff channel for error logs.

**Comment by Dthen** [comment]
Actually, a staff channel might be less annoying. archivist.config would simply need a channel id and then the ability to message.reply() there.

**Comment by Dthen** [comment]
Decided to log to channel instead, closed with commit a03f6f67e258654b951f3380852e46271545c40d
